### ISSUE TITLE
Include Zarr Pixel Buffer

### ISSUE THREAD

**Issue by kkoz** [glencoesoftware/omero-ms-image-region#114]
To remove duplicate code, include omero-zarr-pixel-buffer to remove local ZarrPixelBuffer and OmeroAmazonS3ClientFactory.

**Comment by sbesson** [comment]
@kkoz would you also foresee being able to remove the local `PixelsService` implementation in favour of the class coming with the new dependency?

**Comment by kkoz** [comment]
@sbesson Maybe - the issue is that the microservice doesn't have an IQuery (since it's not in the server), so we have to do a couple things slightly differently to avoid its use. Maybe we should just do those things differently in the `omero-zarr-pixel-buffer` version of the `PixelsService`, but for this step I think it'll stick around.

**Comment by chris-allan** [comment]
Closed by #137.
