### ISSUE TITLE
Label Image Metadata API call returns status code 200 on failure

### ISSUE THREAD

**Issue by knabar** [glencoesoftware/omero-ms-image-region#129]
Example URL:

https://v2-demo-dev.glencoesoftware.com/omero_ms_image_region/get_label_image_metadata/787391

Returns 200 status code:

![Screenshot 2023-06-28 at 14 05 22](https://github.com/glencoesoftware/omero-ms-image-region/assets/197099/e6552b73-9dd7-459b-87d0-1d71e4d1bdea)

Content is error message:

![Screenshot 2023-06-28 at 14 05 41](https://github.com/glencoesoftware/omero-ms-image-region/assets/197099/71e854c4-8de5-44d9-9956-af594e96e05b)

Expected behavior:  return a 4xx or 5xx error code, depending on actual cause

**Comment by erindiel** [comment]
This label image is missing the expected `lsid`, and is a pre-Generation 3 NGFF label image:

```
 # | Class         | Id    | details               | entityId | entityType | uuid                                 
---+---------------+-------+-----------------------+----------+------------+--------------------------------------
 0 | ExternalInfoI | 11991 | owner=2052;group=1953 | -1       | zarr       | 841d382d-1db6-4c6e-b762-0e025c916fae 
(1 row)
```

For a functional Generation 3 NGFF label image:
```
 # | Class         | Id    | details               | entityId | entityType                           | lsid                                                                      | uuid                                 
---+---------------+-------+-----------------------+----------+--------------------------------------+---------------------------------------------------------------------------+--------------------------------------
 0 | ExternalInfoI | 14164 | owner=2052;group=1953 | 3        | com.glencoesoftware.ngff:multiscales | /data/ngff-erin/113354.zarr/0/labels/6aad5566-c90f-41b2-95f4-cc9dad48b170 | 6aad5566-c90f-41b2-95f4-cc9dad48b170 
(1 row)
```

**Comment by knabar** [comment]
Just ran into this issue again with an image that just has regular masks, so the error message is valid, but things break because of the 200 status code (and PathViewer not doing proper error handling because of that)
